### ISSUE TITLE
chewingContext AttributeError: 'NoneType' object has no attribute 'set_addPhraseDirection'

### ISSUE THREAD

**Issue by tonysan** [EasyIME/PIME#638]
Trace:

```
[2021-05-31 00:02:11.539] [PIMELauncher] [error] [Backend error] Traceback (most recent call last):
  File "server.py", line 87, in run
    ret = client.handleRequest(msg)
  File "server.py", line 50, in handleRequest
    reply = service.handleRequest(msg)
  File "C:\Program Files (x86)\PIME\python\textService.py", line 90, in handleRequest
    self.checkConfigChange()  # check if configurations are changed
  File "C:\Program Files (x86)\PIME\python\input_methods\chewing\chewing_ime.py", line 113, in checkConfigChange
    self.applyConfig()
  File "C:\Program Files (x86)\PIME\python\input_methods\chewing\chewing_ime.py", line 121, in applyConfig
    chewingContext.set_addPhraseDirection(cfg.addPhraseForward)
AttributeError: 'NoneType' object has no attribute 'set_addPhraseDirection'
```

**Comment by ottokang** [comment]
請問有復現的方式嗎？測試了設定並沒有看到類似的錯誤訊息
