### ISSUE TITLE
關於我 Windows 10 中英切換格子消失，也無法用 Shift 切換的狀況

### ISSUE THREAD

**Issue by DdavidC** [EasyIME/PIME#689]
很多人應該都回報過相關的類似 Bug，我只是多花了一點時間去看一下我自己的狀況，但別人的狀況不一定是同樣的。
我就是看了一下 PIME 的 debug log，長這樣。

```
[2022-01-25 20:39:52.202] [PIMELauncher] [error] [Backend error] Traceback (most recent call last):
  File "D:\anaconda3\envs\common\Lib\site.py", line 73, in <module>
    import os
  File "D:\anaconda3\envs\common\Lib\os.py", line 29, in <module>
    from _collections_abc import _check_methods
  File "D:\anaconda3\envs\common\Lib\_collections_abc.py", line 12, in <module>
    GenericAlias = type(list[int])
TypeError: 'type' object is not subscriptable

[2022-01-25 20:39:52.251] [PIMELauncher] [error] [Backend error] Fatal Python error: init_import_size: Failed to import the site module
Python runtime state:
[2022-01-25 20:39:52.251] [PIMELauncher] [error] [Backend error]  initialized

[2022-01-25 20:39:52.251] [PIMELauncher] [error] [Backend error] Traceback (most recent call last):
  File "D:\anaconda3\envs\common\Lib\site.py", line 73, in <module>
    import os
  File "D:\anaconda3\envs\common\Lib\os.py", line 29, in <module>
    from _collections_abc import _check_methods
  File "D:\anaconda3\envs\common\Lib\_collections_abc.py", line 12, in <module>
    GenericAlias = type(list[int])
TypeError: 'type' object is not subscriptable
```

呃，問題看起來超明顯的。因為我開始發生問題的時間點，剛好是我重裝了 Python （用 anaconda 版本），並且設定了一個叫 common 的虛擬環境之後。很清楚可以看到 run PIMELauncher 時它跑去找我的這個 common Python 環境了，而這環境缺少它要的東西，所以掛掉了。我因為自己的需求，把環境變數 PYTHONPATH 設定給這個 common 環境跟其他自己的目錄，這也許就是它找過去的原因：

```
D:\anaconda3\envs\common\Lib;D:\anaconda3\envs\common\DLLs;E:\Program\Python;
```

沒錯，只要我把自己設定的 PYTHONPATH 拔掉，重新 Run PIMELauncher，它就正常了。因此這可能是部份人切換失效的原因，因為他們自己也有裝 Python 並設定 PYTHONPATH，或者是因為某些其他原因讓 Python 搜尋路徑變動了，導致 PIME 找不到自己安裝目錄下的那一份虛擬環境。

另外，我也試過重裝 PIME，似乎可以讓它復活，但重開機後無法切換的問題又回來了，它又去找我的 common 環境了。

另外我又去看了一下它在工作管理員裡的情況。

[https://i.imgur.com/i61TTL2.jpg](url)

我發現 Windows 10 內建的 Windows Defender 在相對比較用力地動起來。如果我去關掉它（下面這張圖同時可以看到下面有兩個 Runtime Broker，都是跑 PIMELauncher 切輸入法會長出來的，而且會越長越多個）：

[https://i.imgur.com/YHeASxE.jpg](url)

會發現 Windows Defender 就收工了，CPU 總使用率也從 40% 掉回正常的 10%。

[https://i.imgur.com/k7Gy2KI.jpg](url)

推測我這邊可能的狀況主要就是，PIME 沒有成功綁定到自己的環境（應該是要綁定安裝目錄下的那一份 Python 吧），所以執行過程中一直會出現找不到特定某些物件的錯誤，然後看來會持續 Retry 但反正不會成功。這個就是我切換不了的主要問題。我有嘗試對 backends.json 動手腳看是不是靠它可以綁到對的 Python 去，不過因為我不知道內部實際到底怎麼運作的，所以我失敗了，反而只是讓 PIMELauncher 直接徹底跑都跑不起來，只好放棄。

接著，也許它的某些行動會驚動 Windows Defender 覺得怪怪的但最後又沒有真的認為它有問題，這應該是某些人覺得開了 PIME 時執行效率會變差，甚至有些防毒軟體會叫的理由吧。雖然我沒法確定是什麼行為導致的。

以上是我自己的觀察。不知道是不是有其他人是同樣狀況？

**Comment by Ronaldyen** [comment]
我在使用wps - Document 也發現shift 無法切換中/英文的問題, 重開 wps , 問題消失了. 
回報一下相關情況, 供定位問題參考
