### ISSUE TITLE
單字量過多、使用者詞庫無法開啟失去功能

### ISSUE THREAD

**Issue by kuroutaakatsuki** [EasyIME/PIME#715]
目前使用詞庫的單字量大約在6.6萬筆。
家用電腦跟公司電腦的詞庫檔案互相交換累積詞量。

最近發現平常打字沒有問題，但想開啟「編輯使用者詞庫」來輸入詞庫時，會出現永久讀取後，整個程式無法運作、失去打字機能的問題。

從小圖示Restart PIME無法發揮任何功用。
工作管理員可以看到有PIMELauncher跟兩個pythos在運行。

所以我這幾天想輸入詞庫時，會先開啟詞庫，確認無法動作後，
用工作管理員把上述三個處理程序停止，手動把詞庫檔案丟到檔案夾裡，再去開PIME。

**Comment by ottokang** [comment]
是卡在「載入詞庫中、請稍後」畫面嗎？應該不會是 PIMELauncher 的問題，我手上 2 萬多跟 3 萬多筆詞庫的 PIME 都滿正常的

**Comment by kuroutaakatsuki** [comment]
對，進入「載入詞彙中，請稍後...」的畫面後，進入無限讀取。
放著一段時間、或是關掉後，都會讓輸入法會當掉呈現無法打字的狀態。

開啟時，處理程序會有1個PIME Launcher，跟2個Python。
然後無限讀取。
![スクショ 2022-08-09 16-50-11](https://user-images.githubusercontent.com/56618015/183609802-1128d96e-69da-49d3-80c5-8a641aa87633.jpg)
![スクショ 2022-08-09 16-49-51](https://user-images.githubusercontent.com/56618015/183609878-6eb91b22-f697-48a0-84e2-5fe5f44c9b57.jpg)

直接把「編輯使用者詞庫」關掉，再開一次。
詞庫會直接顯示0詞彙。
處理程序為1個PIME Launcher，跟2個Python。
然後死當。
![スクショ 2022-08-09 17-00-51](https://user-images.githubusercontent.com/56618015/183609897-bb958d6a-49b0-4786-b79d-780e63af7a13.jpg)
![スクショ 2022-08-09 16-50-29](https://user-images.githubusercontent.com/56618015/183609919-59ffe753-dc6b-4256-bc8e-4042dc591177.jpg)

目前最多看到跑出3個Python的狀況。
![スクショ 2022-08-09 17-00-43](https://user-images.githubusercontent.com/56618015/183610062-7a87684e-e3d2-45be-a086-4ab5c6ae4586.jpg)

我最後一次有成功進入的時候，詞彙量是65648筆。
現在應該有到6.6萬筆。
開啟sqlite3檔裡面的ROWID目前跑到1300407。
![181425172-afa8e0a4-7f2d-403d-915e-87659d06295e](https://user-images.githubusercontent.com/56618015/183610652-02bc0ee9-aedf-4a8f-95a4-ae12f6ebdecf.jpg)

**Comment by ottokang** [comment]
這邊如果方便的話，可能要請你提供詞庫 SQLite 檔案來測試看看，裡面會有你的打字資訊，這請你再參酌一下。

或者是你提供在「載入詞庫中，請稍後」，按 F12，提供瀏覽器主控台的錯誤訊息參考。

**Comment by kuroutaakatsuki** [comment]
沒問題，我傳到我的Google Drive。
過一陣子會刪掉。
https://drive.google.com/drive/folders/1BS9rXbD-WxC3ZcRzUSLm23Lmz5vx1Pac?usp=share_link

覺得應該是詞彙筆數過多，超出UI的處理負荷吧。
再麻煩您研究了。

────
順便再題一下，詞彙優先度的參數設計，覺得還可以再調整一下。
這點在 Issues #713有提到。

感謝開發及維護的各位！

**Comment by ottokang** [comment]
已經下載了，再研究看看是什麼問題

**Comment by ottokang** [comment]
目前看應該是 libchewing 的問題，不過也可能是詞庫中有不能接受的字元導致錯誤，要再查了

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\PIME\python\python3\tornado\web.py", line 1711, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:\Program Files (x86)\PIME\python\python3\tornado\web.py", line 3208, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Program Files (x86)\PIME\python\input_methods\chewing\config_tool.py", line 141, in get
    while chewing_ctx.userphrase_has_next(byref(phrase_len), byref(bopomofo_len)):
OSError: exception: access violation reading 0x00000000
```

**Comment by yan12125** [comment]
看了一下 `chewing_userphrase_has_next` 的 code，比較有可能出現 `access violation reading 0x00000000` 的地方可能是在計算 phrase 長度的地方 [1]。如果詞庫沒有正確修改，造成有一些條目的 phrase 是 NULL，就會出現這個問題。請問可以確認一下你的詞庫是否有這樣的條目呢？可以用以下的 SQL statement 檢查：
```SQL
SELECT * FROM userphrase_v1 WHERE phrase IS NULL;
```
[1] https://github.com/chewing/libchewing/blob/452f6221fbad90c0706a3963b17e226216e40dd7/src/chewingio.c#L1940

**Comment by kuroutaakatsuki** [comment]
事隔4個月，不小心點到使用者詞庫，發現竟然可以開了。
功能正常。

83504 個詞彙
開啟時間約5秒

不清楚為什麼突然好了，做個回報。
![Snipaste_2023-11-18_04-28-55](https://github.com/EasyIME/PIME/assets/56618015/37526f20-49eb-4044-8803-a604a19c9574)

**Comment by kuroutaakatsuki** [comment]
詞庫字數一多又掛掉了。XD
做個回報。

用其他程式開chewing.sqlite3確認詞庫字數為91214筆。
![Snipaste_2024-04-27_05-49-14](https://github.com/EasyIME/PIME/assets/56618015/6eff68a8-17f9-4989-95bf-1911f979b537)

**Comment by kuroutaakatsuki** [comment]
2024/08/15
又恢復正常了。

共 93947 個詞彙
![2024-08-15_10-47-37](https://github.com/user-attachments/assets/3f3fee6c-b8cf-4b0d-bc2e-7e71fb0e2810)
